### ISSUE TITLE
Essential tweaks not working properly

### ISSUE THREAD

**Issue by RolittapesReal** [ChrisTitusTech/win10script#299]
Whenever I run essential tweaks in PowerShell it shows until showing task manager details and the scripts just stops there. I let it stay like that for an hour still it did not do anything.
![image](https://user-images.githubusercontent.com/77779356/157991693-85aa1285-4993-4a32-97cc-e565a41bb728.png)

**Comment by micziz** [comment]
Are you running a windows insider build? Or just stable win11?

**Comment by SimPilotAdamT** [comment]
Happens for me on Windows 11 Dev insider build 22579, on a VM, several laptops and my desktop. Started happening for me o a couple of builds ago, when MS released the Task Manager redesign. I'd assume that @RolittapesReal is using a similar build.

![image](https://user-images.githubusercontent.com/71192298/159159449-208eb3f9-0176-4d6c-a3e9-e49966e18791.png)

![image](https://user-images.githubusercontent.com/71192298/159159467-269f4d64-f73a-4a6d-bd29-ecf83ee792f9.png)

**Comment by SimPilotAdamT** [comment]
Should be fixed in #304

**Comment by RolittapesReal** [comment]
No it is still not fixed still same issue. My windows version in given in the image
![image](https://user-images.githubusercontent.com/77779356/159226201-67476e61-33a6-4faf-bfa0-804004300e25.png)

**Comment by SimPilotAdamT** [comment]
> No it is still not fixed still same issue. My windows version in given in the image

Did you ctrl+c then ctrl+v the code I committed there or did you rerun the script from the link given in the readme?

**Comment by SimPilotAdamT** [comment]
@RolittapesReal try running the following code by copy-pasting it into a PowerShell prompt. If my fix works, there should be no output at all.

```
If ((get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name CurrentBuild).CurrentBuild -lt 22557) {
    	Write-Host "Showing task manager details..."
    	$taskmgr = Start-Process -WindowStyle Hidden -FilePath taskmgr.exe -PassThru
    	Do {
      		Start-Sleep -Milliseconds 100
        	$preferences = Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\TaskManager" -Name "Preferences" -ErrorAction SilentlyContinue
    	} Until ($preferences)
    	Stop-Process $taskmgr
    	$preferences.Preferences[28] = 0
    	Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\TaskManager" -Name "Preferences" -Type Binary -Value $preferences.Preferences
    }
```

**Comment by RolittapesReal** [comment]
Yea there was no output now what should I do??

**Comment by SimPilotAdamT** [comment]
> Yea there was no output now what should I do??

That means my fix worked. It means that it skipped the Task Manager thing because you have the latest Task Manager from that build of Windows 11. It skipped that which means that once that pull request is merged, you can run the essential tweaks and everything will run, it won't hang on Task Manager.

**Comment by RolittapesReal** [comment]
Ok so now After running your fix I should try essentiaal tweaks agin??

**Comment by SimPilotAdamT** [comment]
> Ok so now After running your fix I should try essential tweaks again??

No, that will only get stuck. Just wait for #304 to be merged.

**Comment by RolittapesReal** [comment]
ok

**Comment by RolittapesReal** [comment]
How long will #304 take to be merged??

**Comment by SimPilotAdamT** [comment]
It depends on the maintainers....

**Comment by SimPilotAdamT** [comment]
Hey @RolittapesReal should be good to go to run the script
